bob_trigg_parkside:
    resource: "@BobTriggParksideBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

loan:
    path:   /loan
    defaults: { _controller: BobTriggParksideBundle:Loan:index }